name: Django CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Files to EC2 - Blue
        run: |
          scp -o StrictHostKeyChecking=no -r * ubuntu@${{ secrets.EC2_BLUE_HOST }}:/home/ubuntu/backend-django

      - name: Copy Files to EC2 - Green
        run: |
          scp -o StrictHostKeyChecking=no -r * ubuntu@${{ secrets.EC2_GREEN_HOST }}:/home/ubuntu/backend-django

      - name: SSH and Deploy - Blue
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_BLUE_HOST }} << 'EOF'
          cd /home/ubuntu/backend-django
          docker-compose down
          docker-compose up --build -d
          EOF

      - name: SSH and Deploy - Green
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_GREEN_HOST }} << 'EOF'
          cd /home/ubuntu/backend-django
          docker-compose down
          docker-compose up --build -d
          EOF

      - name: Switch Traffic to Green
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PROXY_HOST }} << 'EOF'
          sudo sed -i 's/proxy_pass http:\/\/blue;/proxy_pass http:\/\/green;/' /etc/nginx/nginx.conf
          sudo systemctl reload nginx
          EOF
